FROM photon:3.0
RUN echo "proxy=http://10.6.10.156:8118">> /etc/tdnf/tdnf.conf
RUN tdnf install -y cronie rsyslog logrotate shadow tar gzip sudo >> /dev/null\
    && mkdir /var/spool/rsyslog \
    && groupadd -r -g 10000 syslog && useradd --no-log-init -r -g 10000 -u 10000 syslog \
    && tdnf clean all
