FROM photon:3.0
RUN echo "proxy=http://10.6.10.156:8118">> /etc/tdnf/tdnf.conf
RUN tdnf install -y python3 python3-pip httpd && tdnf clean all
RUN pip3 install --upgrade setuptools -i https://mirrors.aliyun.com/pypi/simple/
RUN pip3 install setuptools && pip3 install pipenv==2018.11.26 -i https://mirrors.aliyun.com/pypi/simple/
