FROM photon:3.0
RUN echo "proxy=http://10.6.10.156:8118">> /etc/tdnf/tdnf.conf
RUN tdnf install -y shadow sudo \
    && tdnf clean all \
    && groupadd -r -g 10000 notary \
    && useradd --no-log-init -r -g 10000 -u 10000 notary
