FROM photon:3.0
RUN echo "proxy=http://10.6.10.156:8118">> /etc/tdnf/tdnf.conf
RUN tdnf install sudo -y >> /dev/null\
    && tdnf clean all \
    && mkdir -p /etc/registry \
    && groupadd -r -g 10000 harbor && useradd --no-log-init -m -g 10000 -u 10000 harbor