FROM photon:3.0
RUN echo "proxy=http://10.6.10.156:8118">> /etc/tdnf/tdnf.conf
RUN tdnf install -y git shadow sudo rpm xz python-xml >>/dev/null\
    && tdnf clean all \
    && groupadd -r -g 10000 clair \
    && useradd --no-log-init -m -g 10000 -u 10000 clair